### ISSUE TITLE
Erro 503

### ISSUE THREAD

**Issue by raisiqueira** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#1]
Iniciei este docker-compose.yml junto com o outro repositório seu (WordPress), porém está retornando um erro 503.
```
nginx-letsencrypt    | Sleep for 3600s
nginx-letsencrypt    | 2017/07/03 19:14:50 Generated '/app/letsencrypt_service_data' from 1 containers
nginx-letsencrypt    | 2017/07/03 19:14:50 Running '/app/update_certs'
nginx-letsencrypt    | 2017/07/03 19:14:50 Watching docker events
nginx-letsencrypt    | Sleep for 3600s
nginx-letsencrypt    | 2017/07/03 19:14:50 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
nginx-letsencrypt    | 2017/07/03 19:14:53 Received event start for container ca91608a7e3c
nginx-letsencrypt    | 2017/07/03 19:14:53 Received event start for container 34921ddf8dcc
nginx-letsencrypt    | 2017/07/03 19:15:08 Debounce minTimer fired
nginx-letsencrypt    | 2017/07/03 19:15:08 Generated '/app/letsencrypt_service_data' from 3 containers
nginx-letsencrypt    | 2017/07/03 19:15:08 Running '/app/update_certs'
nginx-letsencrypt    | Reloading nginx docker-gen (using separate container nginx-gen)...
nginx-letsencrypt    | Reloading nginx (using separate container nginx)...
nginx-letsencrypt    | Creating/renewal api.laboratorioimec.com.br certificates... (api.laboratorioimec.com.br)
nginx-letsencrypt    | 2017-07-03 19:15:09,650:INFO:simp_le:1213: Generating new account key
nginx-letsencrypt    | 2017-07-03 19:15:15,360:WARNING:simp_le:1304: api.laboratorioimec.com.br was not successfully self-verified. CA is likely to fail as well!
nginx-letsencrypt    | 2017-07-03 19:15:15,635:INFO:simp_le:1314: Generating new certificate private key
nginx-letsencrypt    | 2017-07-03 19:15:17,641:ERROR:simp_le:1272: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/0x9Ne278n4l3MKpJ_DBCmTuIIH2qc_M5hCHkGeYNHJ4
nginx-letsencrypt    | Challenge validation has failed, see error log.
nginx-letsencrypt    | 
nginx-letsencrypt    | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx-letsencrypt    | Creating/renewal laboratorioimec.com.br certificates... (laboratorioimec.com.br)
nginx-letsencrypt    | 2017-07-03 19:15:18,324:INFO:simp_le:1213: Generating new account key
nginx-letsencrypt    | 2017-07-03 19:15:22,717:WARNING:simp_le:1304: laboratorioimec.com.br was not successfully self-verified. CA is likely to fail as well!
nginx-letsencrypt    | 2017-07-03 19:15:22,992:INFO:simp_le:1314: Generating new certificate private key
nginx-letsencrypt    | 2017-07-03 19:15:23,450:ERROR:simp_le:1272: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/DG97RDg-vDKjJ_TzrREimxn3OSyCrsFVaXH2OpXV1uk
nginx-letsencrypt    | Challenge validation has failed, see error log.
nginx-letsencrypt    | 
nginx-letsencrypt    | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx-letsencrypt    | Sleep for 3600s

```

**Comment by evertramos** [comment]
Creio que esqueceu de configurar o arquivo `docker-compose.yml` com seu domínio, no log vejo que está tentando validar o domínio:

```
http://example.com
```

Atualize o arquivo com seu domínio e veja se funciona.

**Comment by raisiqueira** [comment]
Agora está retornando "Redirecionamento em Excesso". esse é meu docker-compose:

```yml
version: '3'
services:
  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/nginx/certs:/etc/nginx/certs:ro
  
  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

  site:
    build: ../proxy3/c
    environment:
      VIRTUAL_HOST: laboratorioimec.com.br,www.laboratorioimec.com.br
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 443
      LETSENCRYPT_HOST: laboratorioimec.com.br, www.laboratorioimec.com.br
      LETSENCRYPT_EMAIL: rai@laboratorioimec.com.br

```
eu uso o cloudflare, será que o loop de redirecionamento pode ser o CloudFlare?
