### ISSUE TITLE
Settings for the root domain

### ISSUE THREAD

**Issue by MacGyver27** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#114]
Hi,

Works as expected on for the subdomains. However I cannot make it work when I want a container to be mapped to the root domain itself. 

In this scenario I want Ghost blog to be mapped to the domain I own:
```
version: '3.1'

services:
  
  ghost:
    container_name: ghost
    image: ghost:latest
    #build: ./ghost
    ports:
      - 2368:2368
    volumes:
      - ./content:/var/lib/ghost/content
      - ./config.production.json:/var/lib/ghost/config.production.json
    environment:
      - "NODE_ENV=production"
      - "MYSQL_DATABASE=ghost"
      - "MYSQL_USER=ghost"
      - "MYSQL_PASSWORD=xxxxxxxxxx"
      - "VIRTUAL_PORT=2368"
      - "VIRTUAL_HOST=example.com"
      - "LETSENCRYPT_HOST=example.com"
    depends_on:
      - ghost_db
    restart: always
```

Any suggestions on that?

Thanks, Michal
