### ISSUE TITLE
Internal network marked 'down' incorrectly

### ISSUE THREAD

**Issue by brianhall** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#119]
# Error description:
I've got several services working great using this setup (thanks for your work!) However I've got one service not working properly, and I'm having a hard time diagnosing. I've got the following docker-compose file for the service [gogs](https://gogs.io/):

```
version: '3'

services:
  gogs:
    container_name: gogs
    image: gogs/gogs:latest
    restart: always
    ports:
      - "9022:22"
      - "9007:3000"
    networks:
      - reverse_proxy
    environment:
      VIRTUAL_HOST: my.subdomain.com
      LETSENCRYPT_HOST: my.subdomain.com
      LETSENCRYPT_EMAIL: my@email
      VIRTUAL_PORT: 9007
    volumes:
      - /data/services/gogs:/data

networks:
  reverse_proxy:
    external:
      name: webproxy
```

I'm able to connect at 127.0.0.1:9007, but not from the given subdomain. When I look at the `conf.d/default.conf` output by nginx-gen, I see the corresponding entry:

```
# my.subdomain.com
upstream my.subdomain.com {
  ## Can be connected with "webproxy" network
  # gogs
  server 172.19.0.4 down;
}
``` 

# Expected result

I would expect the upstream to be something like:

```
upstream my.subdomain.com {
  ## Can be connected with "webproxy" network
  # gogs
  server 172.19.0.4:3000;
}
```

And if I change that configuration manually and restart `nginx-web`, the subdomain works just fine. Any thoughts on getting nginx-gen to recognize the upstream? Thanks in advance!
