### ISSUE TITLE
This repo support ECS?

### ISSUE THREAD

**Issue by wizardnet972** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#123]
I love this repo idea and I want to implement using ECS. (AWS) this is my docker-compose file (I run thought `ecs-cli`)
```
version: '3'
services:
  app:
    image: httpd:alpine
    environment: 
      - VIRTUAL_HOST=mydomain.net
      - LETSENCRYPT_HOST=mydomain.net
      - LETSENCRYPT_EMAIL=mydomain@gmail.com
    networks: 
      - net

  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    # container_name: nginx-web:-nginx-web
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /nginx-data/conf.d:/etc/nginx/conf.d
      - /nginx-data/vhost.d:/etc/nginx/vhost.d
      - /nginx-data/html:/usr/share/nginx/html
      - /nginx-data/certs:/etc/nginx/certs:ro
      - /nginx-data/htpasswd:/etc/nginx/htpasswd:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    # container_name: nginx-gen:-nginx-gen
    restart: always
    volumes:
      - /nginx-data/conf.d:/etc/nginx/conf.d
      - /nginx-data/vhost.d:/etc/nginx/vhost.d
      - /nginx-data/html:/usr/share/nginx/html
      - /nginx-data/certs:/etc/nginx/certs:ro
      - /nginx-data/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      
  nginx-letsencrypt:
      image: jrcs/letsencrypt-nginx-proxy-companion
      # container_name: nginx-letsencrypt:-nginx-letsencrypt
      restart: always
      volumes:
        - /nginx-data/conf.d:/etc/nginx/conf.d
        - /nginx-data/vhost.d:/etc/nginx/vhost.d
        - /nginx-data/html:/usr/share/nginx/html
        - /nginx-data/certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
        NGINX_DOCKER_GEN_CONTAINER: nginx-gen
        NGINX_PROXY_CONTAINER: nginx-web

networks:
  net:
    driver: overlay
```

But it's failed:
```
d791482764e6        jrcs/letsencrypt-nginx-proxy-companion

[ec2-user@ip-0-0-0-0 /]$ docker logs d791482764e6
Info: Custom Diffie-Hellman group found, generation skipped.
Reloading nginx docker-gen (using separate container nginx-gen)...
{"message":"Cannot kill container: nginx-gen: No such container: nginx-gen"}
Reloading nginx (using separate container b87faac25c90bf1faec73efd3f5da9db6c3943f789c12c8016abfb658866fdbb)...
Sleep for 3600s
```
