### ISSUE TITLE
Get HTTP 503 when requesting SSL Certificate, besides the use of VIRTUAL_PORT

### ISSUE THREAD

**Issue by bjesuiter** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#144]
# Error description:
I want to run the [shlinkio/shlink:latest](https://hub.docker.com/r/shlinkio/shlink) container on my server with your nginx reverse proxy setup. 

Problem: The Letsencrypt Validation Service gets a 503 error from nginx-web container when it tries to access the ACME Challenge

# Steps to reproduce

1. I use the following docker-compose.yaml

```
version: '3'

volumes:
  db:

networks:
  shlink:
  webproxy:
    external:
      name: webproxy

services:
  db:
    container_name: shlink-url-db
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      # from env files
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - shlink

  shlink-url-shortener:
    image: shlinkio/shlink:latest
    container_name: shlink-url-shortener
    environment:
      # Shlink Config
      SHORT_DOMAIN_HOST: ${SERVICE_DOMAIN}
      SHORT_DOMAIN_SCHEMA: https
      # The name of a query param that can be used to visit short URLs avoiding the visit to be tracked.
      DISABLE_TRACK_PARAM: notrack
      # Reverse Proxy Settings
      VIRTUAL_HOST: ${SERVICE_DOMAIN}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${SERVICE_DOMAIN}
      LETSENCRYPT_EMAIL: bjesuiter@gmail.com
      # DB Settings
      DB_DRIVER: mysql
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - webproxy
      - shlink
```

2. The .env File for this docker-compose is 

```
# Global Vars
SERVICE_DOMAIN=links.avil.io

# Mariadb Setup Vars
MYSQL_ROOT_PASSWORD=someMariaDBrootPW

# Shared Setup Vars between MariaDB & Shlink
MYSQL_DATABASE=shlink
MYSQL_USER=shlink
MYSQL_PASSWORD=someMySQLPW
```

4. Change the SERVICE_DOMAIN var when running these test files 
4. Change the LETSENCRYPT_EMAIL to a personal one instead of mine.
3. Run `docker-compose up -d` to start the thingy 

# Expected result
The ACME Challenge can be executed successfully.

# Error result
The Letsencrypt Validation Service gets a 503 error from nginx-web container when it tries to access the ACME Challenge

# Comments (Things I checked and tried)

1. I added all necessary config to the shlink container, being: 

    - env var VIRTUAL_HOST: ${SERVICE_DOMAIN}
    - env var VIRTUAL_PORT: 8080
    - env var LETSENCRYPT_HOST: ${SERVICE_DOMAIN}
    - env var LETSENCRYPT_EMAIL: bjesuiter@gmail.com
    - use network webproxy 
    - expose port "8080" (besides being already exposed through the dockerfile of shlink)

2. I especially used the VIRTUAL_PORT env var
3. I deleted all previously generated folders for `links.avil.io` in nginx-data/certs folder to have a fresh starting point. 

# Suggestion

As a follow up suggestion to this issue: 
Do you want to create some kind of FAQ File, which answers the most asked questions? 
It's the second time now that i encounter this problem. 
I fixed it the first time by re-cloning the repository and deleting the data folder. 
But i don't want to re- setup the whole reverse-proxy-system each time i encounter this error. 

My feeling tells me, that the system seems confused if it can't connect to the service container on the very first certificate request. But i can't proof this. 

Anyway, the FAQ should have a section for 

> ## I get a HTTP error 503 when ACME Challenge is validated? 
> This could mean:
> ### 1. A connection error between the reverse proxy and your service container. 
> -  Is your VIRTUAL_PORT property set when service container runs on a port other than 80?
> ### 2. ...
