### ISSUE TITLE
Second website on a multiple website setup is not working

### ISSUE THREAD

**Issue by Darksoulsong** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#174]
# Error description:
I'm using [this](https://github.com/evertramos/docker-wordpress-letsencrypt) docker setup for Wordpress together with https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion locally for two websites (site1 and site2). Site1 works as expected, site2 don't, the browser can't reach it.

# Steps to reproduce
- Clone the https://github.com/evertramos/docker-wordpress-letsencrypt repo and follow the instructions
- Clone the https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion and follow the README instructions
- Clone the config from the first website and db and change the variables and properties
- Put them up `docker-compose up -d`
- Navigate to your site1.local [works] 
- Navigate to your site2.local [fails!] 

# Expected result
- Navigation should occur for both websites

# Error result
The browser can't resolve the address http://site2.local

# Website 1 WP Config
```yaml
networks:
  default:
    external:
      name: webproxy
services:
  db:
    container_name: db1
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: user_pwd
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: user
    image: mariadb:latest
    restart: unless-stopped
    volumes:
    - /Users/user/Documents/sandbox/www/site1/data/db:/var/lib/mysql:rw
  website:
    container_name: site1
    depends_on:
    - db
    environment:
      LETSENCRYPT_EMAIL: mail@gmail.com
      LETSENCRYPT_HOST: site1.local,www.site1.local
      VIRTUAL_HOST: site1.local,www.site1.local
      WORDPRESS_DB_HOST: db1:3306
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_PASSWORD: user_pwd
      WORDPRESS_DB_USER: user
      WORDPRESS_TABLE_PREFIX: wp1
    image: wordpress:latest
    logging:
      options:
        max-size: 200k
    restart: unless-stopped
    volumes:
    - /Users/user/Documents/sandbox/www/site1/data/wordpress-core:/var/www/html:rw
    - /Users/user/Documents/sandbox/www/site1/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:rw
    - /Users/user/Documents/sandbox/www/site1/conf.d/uploadsize.ini:/usr/local/etc/php/conf.d/uploadsize.ini:rw
version: '3.1'
````

## Website 2 WP Config
```yaml
networks:
  default:
    external:
      name: webproxy
services:
  db:
    container_name: db2
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: user_pwd
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: user
    image: mariadb:latest
    restart: unless-stopped
    volumes:
    - /Users/user/Documents/sandbox/www/site2/data/db:/var/lib/mysql:rw
  website:
    container_name: site2
    depends_on:
    - db
    environment:
      LETSENCRYPT_EMAIL: mail@gmail.com
      LETSENCRYPT_HOST: site2.local,www.site2.local
      VIRTUAL_HOST: site2.local,www.site2.local
      WORDPRESS_DB_HOST: db2:3306
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_PASSWORD: user_pwd
      WORDPRESS_DB_USER: user
      WORDPRESS_TABLE_PREFIX: wp2
    image: wordpress:latest
    logging:
      options:
        max-size: 200k
    restart: unless-stopped
    volumes:
    - /Users/user/Documents/sandbox/www/site2/data/wordpress-core:/var/www/html:rw
    - /Users/user/Documents/sandbox/www/site2/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:rw
    - /Users/user/Documents/sandbox/www/site2/conf.d/uploadsize.ini:/usr/local/etc/php/conf.d/uploadsize.ini:rw
version: '3.1'
```

**Comment by Darksoulsong** [comment]
After I put the site2 up, I restarted the nginx-web container with `docker-compose restart` and `docker exec -it nginx-web nginx -s reload`. 

None of this worked and site2 is still unavailable.

**Comment by shrthnd** [comment]
@Darksoulsong if you run `docker-compose logs` or watch the project on start (`docker-compose up` without the `-d`) from the project root does anything stand out to you? 

I ran into a similar problem when trying to run multiple containers from the same base image. For whatever reason WordPress would swap the database connection between two running containers. This resulted in all content from either website being displayed on either domain at random. 

In my case I was running `wordpress:php7.3-fpm-alpine` with `mariadb:latest` behind and `nginx:alpine` proxy. Also, the problem only occurred between _separate_ projects managed with unique docker-compose files. But... something here might help.

One problem I had to fix was my `wp-config.php` was referencing the database container through the service-name defined in `docker-compose.yml`("db:3306"). I changed this to reference the container name defined in the .env. 

The problem wasn't actually resolved until I created a local `Dockerfile` for each service (which could be a simple one-line reference to the base image.)

Here's the contents of the WP `Dockerfile` created at `./docker/wordpress/`:

```
FROM wordpress:php7.3-fpm-alpine
# wordpress:latest

// ...additional image configuration
``` 

and the `docker-compose.yml`: 

```
version: '3'
services:
  db:
    container_name: ${MYSQL_CONTAINER_NAME}
    #image: mariadb:latest
    build: ./docker/db
    volumes:
      #- ./mysql-dump:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    depends_on:
      - db
    container_name: ${WP_CONTAINER_NAME}
    #image: wordpress:php7.3-fpm-alpine
    build: ./docker/wordpress
    restart: unless-stopped
    volumes:
      - ${WP_PATH}:/var/www/html/
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_CONTAINER_NAME}:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    #image: nginx:alpine
    build: ./docker/nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
networks:
    default:
       external:
         name: ${NETWORK}
```

**Comment by Darksoulsong** [comment]
@shrthnd Thanks for your comment. I'm already referencing the database as the container name. I have some msql errors in the site2 container, but the same happens to site1 and this isn't keeping it from working. And I've checked the generated wp_config files from both websites, and the references to each website configuration seem to be concise.

It seems the WP setup is working as it should, I bet the issues is with by the proxy itself. But I may be wrong.

Here goes my proxy configuration:

```yaml
version: '3.0'

services:
  nginx-gen:
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    image: jwilder/docker-gen
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 2m
    restart: always
    volumes:
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx-data/conf.d:/etc/nginx/conf.d:rw
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx-data/vhost.d:/etc/nginx/vhost.d:rw
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx-data/html:/usr/share/nginx/html:rw
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx-data/certs:/etc/nginx/certs:ro
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx-data/htpasswd:/etc/nginx/htpasswd:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  nginx-web:
    container_name: nginx-web
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 4m
    ports:
    - 0.0.0.0:80:80/tcp
    - 0.0.0.0:443:443/tcp
    restart: always
    volumes:
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx-data/conf.d:/etc/nginx/conf.d:rw
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx-data/vhost.d:/etc/nginx/vhost.d:rw
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx-data/html:/usr/share/nginx/html:rw
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx-data/certs:/etc/nginx/certs:ro
    - /Users/user/Documents/sandbox/www/nginx-proxy/nginx-data/htpasswd:/etc/nginx/htpasswd:ro
networks:
  default:
    external:
      name: webproxy
```
