### ISSUE TITLE
Uploading large files (>10M) through nginx proxy?

### ISSUE THREAD

**Issue by fribse** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#207]
# Error description:
Error 
![image](https://user-images.githubusercontent.com/13660621/83249905-9767e400-a1a7-11ea-8ba7-5c31fbf2db93.png)
When uploading a file I get the above message

# Steps to reproduce
Upload a >2M file to a site behind it

# Expected result
An OK

# Error result
Failed upload

# Comments

Hi Evert

I'm trying to get it to allow uploading some really large files through this.
I have a website in DMZ that is forwarded through an nginx behind your setup.
So your nginx forwards to my nginx that forwards to an inside site.

The docker-compose file I've made for this:
```
# web forward for site
  site-url:
    image: nginx
    container_name: site-url
    restart: always
    volumes:
      - "/docker/site:/etc/nginx/conf.d"
#    depends_on:
#      - name_of_all_your_other_services
    environment:
      VIRTUAL_HOST: siteurl
      LETSENCRYPT_HOST: siteurl
      LETSENCRYPT_EMAIL: email
```
In 'my own' nginx conf.d I've given the line:
    client_max_body_size 100M;

To solve this, but how do I get this added to the hosts that is automatically generated by the environment settings?
