### ISSUE TITLE
How this can work with other docker-compose file?

### ISSUE THREAD

**Issue by Luvgreed** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#37]
# Comments
Hello, may I know how should I update the docker-compose file after I run the ./start.sh, many thanks!
I guess I need to add sth like ::
 networks:
        - webproxy

My original docker-compose file  :
```
version: '3'
services:
    botlinker-service:
      image: registry.gitlab.com/liquidsky/hello-bot:v1.0
      working_dir: /code
      volumes:
        - .:/code      
      ports:
        - "80:3000"
      depends_on:
        - mongodb
    mongodb:
      image: "mongo"
      container_name: mongo
      working_dir: /code
      ports:
        - "27020:27017"
```

**Comment by evertramos** [comment]
yep!

You add networks and virtual_host environment, as of this sample:

https://github.com/evertramos/docker-wordpress-letsencrypt/blob/master/docker-compose.yml

**Comment by driverevil** [comment]
But for example, I am trying to run a ghost docker called bitnami, in it's yml file uses port option binding 80:2368, so I delete this lines and run the docker and is running in 2368/TCP , so when I use my VIRTUAL_HOST=xxx.domain.com just get 502 Bad Gateway message, I settled the networks correctly to, I tried expose:2368 also, How can I set the port to listen on 80 port?, Should I change the docker image or something?
Thanks 👍

**Comment by evertramos** [comment]
@driverevil In the containers I ran it autodiscover the open port and forward the connection through port 80 to my container's port. Not sure how you set up. Can you post your compose file so I could test on my side?

**Comment by mikeevstropov** [comment]
Im having the same problem (502 Bad Gateway) but with Jenkins
https://github.com/jenkinsci/docker/blob/master/Dockerfile

```
version: "3"
services:

  jenkins:
    image: jenkins/jenkins:lts
    environment:
        VIRTUAL_HOST: xxx.site.com
        VIRTUAL_PORT: 8080
    networks:
      - webproxy

networks:
  webproxy:
    driver: bridge
```

**Comment by mikeevstropov** [comment]
Sorry, my bad. Network section of docker-compose.yml is incorrect. Working example:

```
version: "3"
services:

  jenkins:
    image: jenkins/jenkins:lts
    environment:
        VIRTUAL_HOST: xxx.site.com
        VIRTUAL_PORT: 8080

networks:
    default:
       external:
         name: webproxy
```
