### ISSUE TITLE
Multiple domains with different kind of containers. Setup roadmap

### ISSUE THREAD

**Issue by perarg** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#43]
# Error description:

Hi,  this issue doesn't describe a bug or something but i am trying to put things in order based on my setup and i suppose many others.

Let's say for example i have 3 websites with 3 different domains. I have example1.com, example2.com and example3.com. I decided to use a folder on my host machine, let's say /mysites and in there there are three folders containing the files of the sites. So a simple setup will be like this:

--- mysites
---- example1.com
---- example2.com
---- example3.com

### 1st question ###
What should i declare at `.env` file in `NGINX_FILES_PATH=/path/to/your/nginx/data` ?

Do i have to declare `NGINX_FILES_PATH=/mysites` and then in each container i have to call `VIRTUAL_ROOT`? For example if i want my first site (example1.com) may i use
```
docker run -d -e VIRTUAL_HOST=example1.com \
              --VIRTUAL_ROOT=example1.com or /mysites/example1.com
              --network=webproxy \
              --name my_app \
              httpd:alpine
```
???

### 2nd question ###
If we accept that the 1st question is replied and i have 3 websites working, a fourth one comes to play. But the fourth one is not a simple, if i can call it that, container with just html or php files. It's a nodejs application for example rocket.chat. An example **docker-compose.yml** would be

```
version: '3.3'

services:
  db:
    image: mongo
    volumes:
      - ./datatest/runtime/db:/data/db
      - ./datatest/dump:/dump
    command: mongod --smallfiles

  rocketchat:
    image: rocketchat/rocket.chat:latest
    environment:
      MONGO_URL: mongodb://db:27017/rocketchat
      ROOT_URL: http://example4.com
      Accounts_UseDNSDomainCheck: "false"
      VIRTUAL_HOST: example4.com
      LETSENCRYPT_HOST: example4.com
      LETSENCRYPT_EMAIL: myemail@gmail.com
    links:
      - db:db
    ports:
      - 3000:3000
    restart: always
  hubot:
    # doesnt matter for now
networks:
    default:
       external:
         name: mywebproxy
```

1. There is no files in any volume or something for `VIRTUAL_ROOT` environment variable. If it is not declared then the /var/www/public will be used based on nginx.tmpl line 165 https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/5fc18d8c2e38ba6cac51e7ba87e47ea507ca2e08/nginx.tmpl#L165

2. What will happen to Let'sEncrypt certificate ? Due to lack of proper `root`, it could not load the files and it couldn't write at .well-known folder, so the challenge will fail.

How can combine all the above ?
