### ISSUE TITLE
Multiple EXPOSE error

### ISSUE THREAD

**Issue by pakokrew** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#44]
# Error description:

Proxy is not working for that configuration. I have another docker container working well with domain & SSL but that one won't by proxified.

# Steps to reproduce

Start the following configuration: 

docker-compose.yml
```yml
  parity:
    image: parity/parity:v1.8.9
    ports:
        -8545:8545
    volumes:
      - ./parity/testnet:/config
      - ${PARITY_DATA_DIR:-./data/parity/testnet}:/data
    entrypoint: ["/config/entry.sh"]
    environment:
      VIRTUAL_HOST: ${DOMAINS:-}
      LETSENCRYPT_HOST: ${DOMAINS:-}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-}

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}

```

I have another container running with basically same configuration but different image and different DOMAINS variable, which works well. 

# Error result

curl answers 502 Bad gateway both on 80 and 443

./data/nginx/conf.d/default.conf
```
... 
# not working
upstream parity.domain.com {
			server 172.18.0.5 down;
...
# working
upstream other.domain.com {
			server 172.18.0.6:4040;
}
...
}
```

# Comments

Note that the parity server is working if I call directly port 8545

Maybe the problem is from parity image exposing multiple ports. 
How the proxy handle this ? Which port it chooses to proxy ?
