### ISSUE TITLE
Can't find Home dir of my Virtualhost

### ISSUE THREAD

**Issue by Meerbi** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#56]
# Error description:
Hello, were i can find the home dir of my  Virtualhost, where the index.html is stored?
Really dumb question but i cant find it....

My Ngnix Data dir is /ngnix/data
There is an Folder namend Html, when i place data here or create an folder namend like the domain it dont works...

# Steps to reproduce

# Expected result

# Error result

# Comments

**Comment by j7an** [comment]
@Meerbi Nginx is just a proxy for other containers. You can use the examples from the README such as the one below to create an Apache container

```
docker run -d -e VIRTUAL_HOST=your.domain.com \
              -e LETSENCRYPT_HOST=your.domain.com \
              -e LETSENCRYPT_EMAIL=your.email@your.domain.com \
              --network=webproxy \
              --name my_app \
              httpd:alpine
```
To mount the `public_html` folder from the host into the Apache htdocs using Docker Compose file, you can use the following example. Make sure to have your HTML, JS, and CSS files in your `public_html` folder before running `docker-compose up -d`
```
version: '3'

services:
  web:
    container_name: YOUR_CONTAINER_NAME
    restart: always
    image: httpd:alpine
    volumes:
      - ./public-html/:/usr/local/apache2/htdocs/:ro
    environment:
      VIRTUAL_HOST: YOUR_DOMAIN_NAME
      LETSENCRYPT_HOST: YOUR_DOMAIN_NAME
      LETSENCRYPT_EMAIL: YOUR_EMAIL_ADDRESS

volumes:
  public-html:

networks:
    default:
       external:
         name: webproxy
```

See example repos from @evertramos on how to create your own docker-compose.yml

https://github.com/evertramos/docker-wordpress-letsencrypt
https://github.com/evertramos/docker-nextcloud-letsencrypt
https://github.com/evertramos/docker-portainer-letsencrypt
