### ISSUE TITLE
acting as load balance to a container already stoped

### ISSUE THREAD

**Issue by TigPT** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#65]
I had a weird bug, that after days of debug I found out that was related with the proxy.

# Error description:
Proxy was balancing request between the a running nginx container and an already closed container, so exactly half of my requests (request yes, request no) was hitting a server error.

# Steps to reproduce
I don't know how to reproduce, but I have it on my machine since, rebooting server or even restarting your proxy don't clean the events on my server and it keeps thinking that that domain name have more then one container associated.

# Expected result
proxy should only be pointing to running containers.

# Comments
I would like to know how I can force clean cache an restart all domains pointers, or see the registered events and be able to manually delete the miss register event that is making my proxy act like a load balancing when only one container should be running on that domain.

Thanks for the help with this problem and for all your work on this project that let me learn docker and have multiple web services running on the same host very easily.

**Comment by j7an** [comment]
@TigPT Can you post your docker command and/or `docker-compose.yml` file for diagnosis?

**Comment by TigPT** [comment]
I only use "docker-compose up -d" and "docker-compose stop"

I have multiple docker-compose.yml but they are all like this:
```
version: '3'

services:
    parse-server-eurogroup-nginx:
      restart: unless-stopped
      image: nginx:1-alpine
      container_name: parse-server-eurogroup-nginx
      volumes:
        - /root/parse-server-eurogroup/site.conf:/etc/nginx/conf.d/default.conf
        - /var/log/nginx/:/var/log/nginx/
        - /root/parse-server-eurogroup/volumes/:/var/www/html/eurogroup.tig.pt
      environment:
        - VIRTUAL_HOST=eurogroup.tig.pt
        - LETSENCRYPT_HOST=eurogroup.tig.pt
        - LETSENCRYPT_EMAIL=mail@tig.pt
networks:
    default:
       external:
         name: webproxy
```
