### ISSUE TITLE
https redirection is not working!

### ISSUE THREAD

**Issue by mmmint** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#68]
# Error description:
When getting the 3 containers (nginx+gen+letsenc) and my app container running, Im not able to get the port 443 to work (ERR_CONNECTION_REFUSED), only 80 works, but unencrypted of course.

App container (changed my domain for anonymity):
```
version: '3'

services:
   gitea:
      container_name: gitea
      image: gitea/gitea:latest
      restart: unless-stopped
      volumes:
         - /media/gitserver/gitea:/data
      environment:
         USER_UID: 1000
         USER_GID: 1000
         VIRTUAL_HOST: mydomain.com
         LETSENCRYPT_HOST: mydomain.com
         LETSENCRYPT_EMAIL: user@mydomain.com
         VIRTUAL_PORT: 3000
      ports:
         - "300:3000"
         - "5622:22"
networks:
    default:
       external:
         name: webproxy
```
The docker-compose-letsencrypt-nginx-proxy-companion .env file is untouched (copied from the .env.sample).

Here the docker ps output:
```
root@mydomain:~# docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                         NAMES
0dd8c1663b3a        gitea/gitea:latest                       "/usr/bin/entrypoint…"   9 minutes ago       Up 9 minutes        0.0.0.0:5622->22/tcp, 0.0.0.0:300->3000/tcp   gitea
ea8eaa89b361        jwilder/docker-gen                       "/usr/local/bin/dock…"   19 minutes ago      Up 15 minutes                                                     nginx-gen
e018bbee5bec        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/entr…"   19 minutes ago      Up 15 minutes                                                     nginx-letsencrypt
04ddb6c557fa        nginx                                    "nginx -g 'daemon of…"   19 minutes ago      Up 15 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp      nginx-web

```
Would be thankfull for any hints. thanks.

**Comment by evertramos** [comment]
When you use Virtual Port ti redirects to this port. So, please try to remove it, check your DNS if poiting to your server, run the service, wait for the certificates being gerenated, you can check on `certs` folder and on the `default.conf`. After that check the 443 port but your container must be listening on that port. 

If you intend to change ports, make sure you have your certificates settled and than add the VIRTUAL_PORT option.

Please advise.

**Comment by jonra1993** [comment]
How did you solve it??? I had this message in the log. It worked before but I made some changes so 
 I removed the nginx-proxy  folder after that I have this problem. There is any method to add my own certificates of cloudflare??

2019-02-27 00:46:29,344:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/vBLa7XVtBw8amjpOho92Xid0yCqJODJWmg5-aqFXF3w


ACME server returned an error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new authz :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits

**Comment by GijsVermarien** [comment]
Thanks for the config file, it worked directly for me! Was struggling to get the port right, but with VIRTUAL_PORT=3000 it worked right away. My config file for reference:
```
version: "3"

services:
  server:
    image: gitea/gitea:latest
    restart: always
    networks:
      - webproxy
    ports:
      - "3000:3000"
      - "2222:22"

    volumes:
      - ./gitea:/data
    environment:
        USER_UID: 0
        USER_GID: 0
        VIRTUAL_HOST: git.somedomain.com
        LETSENCRYPT_HOST: git.somedomain.com
        LETSENCRYPT_EMAIL: somedomain.somedomain@somedomain.com
        VIRTUAL_PORT: 3000


networks:
    gitea:
        external: false
    webproxy:
        external: true
````
