### ISSUE TITLE
Certificate issues with multiple subdomains

### ISSUE THREAD

**Issue by kevinvdburgt** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#69]
# Error description:
The reverse proxy gives the wrong certificate when using subdomains of the same domain. For example, i have foobar1.example.com and foobar2.example.com. When visiting foorbar2.example.com it gives a certificate error that it serves the certificate form foobar1 to the foobar2 subdomain.
<img width="1277" alt="screen shot 2018-05-28 at 16 27 52" src="https://user-images.githubusercontent.com/1987802/40619114-1c7617b6-6294-11e8-906d-c297699385df.png">

# Steps to reproduce
Created 3 sites using subdomains:
- foobar1.example.com
- foobar2.example.com
- foobar3.example.com

(restart the server a few times until it happens, sometimes it happens without restarting at all)

visit foobar2.example.com and it will show the certificate of foobar1.example.com

Used those `docker-compose.yml` config files to test:
```yml
version: '3'

services:
  app:
    image: httpd:alpine
    environment:
      VIRTUAL_HOST: site-a.node3.docker.zdev.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: site-a.node3.docker.zdev.com
      LETSENCRYPT_EMAIL: info@zdev.com
    restart: always
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy
```

```yml
version: '3'

services:
  app:
    image: httpd:alpine
    environment:
      VIRTUAL_HOST: site-b.node3.docker.zdev.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: site-b.node3.docker.zdev.com
      LETSENCRYPT_EMAIL: info@zdev.com
    restart: always
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy
```

```yml
version: '3'

services:
  app:
    image: httpd:alpine
    environment:
      VIRTUAL_HOST: site-c.node3.docker.zdev.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: site-c.node3.docker.zdev.com
      LETSENCRYPT_EMAIL: info@zdev.com
    restart: always
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy
```

# Expected result
That all of the domains uses the correct certificates.

# Error result
Could not find any error in the logs.

# Comments
It works fine for domains like foobar1.com, foobar2.com, foobar3.com .. but when using subdomains of the same domain it will fail after a period of time (mostly after restarting the server).

Sometimes it just works for days, and when the server (CoreOS) restarts itself for updates and stuff it happens to serve the wrong certificates again.
