### ISSUE TITLE
Redirect www to no www

### ISSUE THREAD

**Issue by nyejon** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#7]
Hello, I have managed to get everything working with my web app using your useful companion and guide. Is there a way I can get the www.domain.com to automatically redirect to domain.com?

**Comment by evertramos** [comment]
Hello @nyejon,

The proxy will only forward it to your container, you can manage that in your container. 

If you are using Apache you can use your _sites-enable_ config:

```
<VirtualHost *:80>
    ServerName yourdomain.com
    ServerAlias www.yourdomain.com
    [...]
```

Of use _.htaccess_:
```
RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ http://%1/$1 [R=301,L]
```

If you are using NGINX you could use:

```
server {
    server_name www.example.com;
    return 301 $scheme://example.com$request_uri;
}
```

The settings above should be done in your app containers and at start you must use the correct _VIRTUAL_HOST_ settings in your app container, so it can be proxied:

```
VIRTUAL_HOST: yourdomain.com, www.yourdomain.com
```

**Comment by nyejon** [comment]
Thanks very much! I have it working

**Comment by Fensterbank** [comment]
Hello @evertramos,
I tried this, but I'm ending up in a redirection loop error.
(I replaced my domain by example.com for this comment)

```
    example.com:
        container_name: example.com
        image: nginx:alpine
        restart: always
        volumes:
            - ~/docker/example.com/nginx.conf:/etc/nginx/conf.d/default.conf
            - ~/docker/example.com/html:/usr/share/nginx/html
        environment:
            VIRTUAL_HOST: example.com,www.example.com
            LETSENCRYPT_HOST: example.com
            LETSENCRYPT_EMAIL: foo@example.com
```
This is the content of my nginx.conf to make that redirection from www to non-www

```
server {
    server_name www.example.com;
    return 301 $scheme://example.com$request_uri;
}
```
When I visit www.example.com, I get no redirection, but of course a certificate error.
When I visit example.com, I get a redirect loop.

For me, this makes no sense at all. It's the opposite of my configuration.
Am I missing something here?
