### ISSUE TITLE
Traffic is not being proxied correctly

### ISSUE THREAD

**Issue by philipkobernik** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#73]
# Error description:

Requests to staging.site.com are being routed to site.com!

# Steps to reproduce

1. start nginx-proxy (after copying/updating .env)
2. start service containers using docker-compose:
SITE.COM
```
version: "3"

volumes:
  data:
    external: false

services:
  web:
    environment:
      VIRTUAL_HOST: site.com,www.site.com
      LETSENCRYPT_HOST: site.com,www.site.com
      VIRTUAL_PORT: '80'
    build:
      context: .
      dockerfile: ${NGINX_DOCKERFILE}
    expose:
      - '80'
  db:
    image: mysql:5.7
    volumes:
      - data:/usr/local/mysql/data

networks:
    default:
       external:
         name: 'webproxy'
```

STAGING.SITE.COM
```
version: "3"

volumes:
  data:
    external: false

services:
  web:
    environment:
      VIRTUAL_HOST: staging.site.com
      LETSENCRYPT_HOST: staging.site.com
      VIRTUAL_PORT: '80'
    build:
      context: .
      dockerfile: ${NGINX_DOCKERFILE}
    expose:
      - '80'
  db:
    image: mysql:5.7
    volumes:
      - data:/usr/local/mysql/data

networks:
    default:
       external:
         name: 'webproxy'
```

3. letsencrypt cert issuance works-- but all requests to staging.site.com are somehow flowing to site.com

When I change the 2nd service container to use 1301 instead of 80 and update the virtual port, I get 502 bad gateway.

# Expected result

nginx-proxy routes traffic to correct service container based on the virtual host/port config.

# Error result

Traffic is routed incorrectly-- requests to staging.site.com are flowing to site.com service container

Thanks for your attention!
I'm new to Docker and have the feeling I'm missing something really simple or obvious!
(docker-compose files are quite redacted-- but each site has a web(nginx), app(rails), db(mysq) container-- seems possible that wires are getting crossed on the network level rather than at the proxy level)
