### ISSUE TITLE
New containers with SSL enabled produce SSL_do_handshake() failed

### ISSUE THREAD

**Issue by PJHaynes304** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#88]
# Error description:
When new containers are started with SSL requests return 502 Bad Gateway. Docker logs from nginx_web show the following error: 
(SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream

# Steps to reproduce
Start new container with SSL and send request to url

# Expected result
OK 200

# Error result
502 Bad Gateway
SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream

# Comments
Have even tried with httpd:alpine to rule out any issues with SSL in my container. Have other containers with SSL started last week that are still up and running fine but new containers all fail in the same way.

**Comment by drhaynes** [comment]
+1 experiencing this issue too.

Wondering if it’s a change to the ssl libraries in the official Docker alpine image.

**Comment by evertramos** [comment]
Hello there!

Is this happening only with alpine image?

**Comment by PJHaynes304** [comment]
It was happening with my Image built from JDK:8-alpine so tried it with the http:alpine image. 

Yes starting the web proxy with ./start.sh.

Have just tried pulling everything down and starting again as suggested:- still the same response.

docker-compose.yml for my services:

```
version: '3.6'

services:
  mongo:
    image: mongo
    container_name: docker-mongo2
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always

  springboot:
    image:  $SITE_IMAGE_NAME
    restart: always
    container_name: $SITE_CONTAINER_NAME
    ports:
      - "8081"
    environment:
      VIRTUAL_HOST: $SITE_DOMAIN
      VIRTUAL_PROTO: $HTTPS
      VIRTUAL_PORT: $HTTPS_PORT
      LETSENCRYPT_HOST: $SITE_DOMAIN
      LETSENCRYPT_EMAIL: $SITE_CERTIFICATE_CONTACT
    volumes:
      - $HOME/infrastructure/data/certs:/certs
    working_dir: /opt/app
    depends_on:
      - mongo
    links:
      - mongo

  testcontainer:
    container_name: testcontainer
    build:
      context: .
      dockerfile: Dockerfile-test
    working_dir: /opt/app

networks:
  default:
    external:
      name: webproxy
```

Variables are defined and exported in a .env file as follows(values substituted for actual names and email)

```
export COMPOSE_PROJECT_NAME=projectname
export SITE_DOMAIN=site.domain.com
export HTTPS=https
export HTTPS_PORT=443
export SITE_CERTIFICATE_CONTACT=certificate@contact.com
export SITE_IMAGE_NAME=projectowner/projectname:prod
export SITE_CONTAINER_NAME=containername
```

Sourced when run with docker-compose:
```
'docker-compose rm -f && source .env . && docker-compose up -d mongo springboot'
```
Seems like the webproxy is wired up OK as I can see the requests in the docker logs.
